/*
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/
#include <iostream>
#include <set>
using namespace std;
int main()
{
	set<int> pent;
	int n,flag=0;;
	for (int i = 1; i < 3000; ++i)
	{
		n=(3*i*i-i)/2;
		pent.insert(n);
	}
	for (set<int>::iterator i = pent.begin(); i!=pent.end() ; ++i)
	{
		for (set<int>::iterator j = i; j!=pent.end() ; ++j)
		{
			if(pent.find(*i+*j)!=pent.end() && pent.find(*j-*i)!=pent.end())
			{
				cout<<*j-*i<<"\n";
				flag=1;
				break;
			}
		}
		if(flag==1)break;
	}
	return 0;
}