/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
*/
#include <iostream>
#include <set>
using namespace std;
int main()
{
	set<long> NP,NH;
	long i=286,j=166,k=144;
	long T=(i*i+i)/2,P=(3*j*j-j)/2,H=2*k*k-k;
	do
	{
		NP.insert(P);
		NH.insert(H);
		++i;++j;++k;
		T=(i*i+i)/2;
		P=(3*j*j-j)/2;
		H=2*k*k-k;
	}while(NP.find(T)==NP.end() || NH.find(T)==NH.end());
	cout<<T<<"\n";
	return 0;
}